"""Added book info to answers

Revision ID: 0dd23c5cac46
Revises: e2edeb1251bc
Create Date: 2020-07-23 11:08:45.689143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd23c5cac46'
down_revision = 'e2edeb1251bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_answer', sa.Column('book', sa.String(), nullable=True))
    op.add_column('student_answer', sa.Column('chapter', sa.Integer(), nullable=True))
    op.add_column('student_answer', sa.Column('section', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_answer', 'section')
    op.drop_column('student_answer', 'chapter')
    op.drop_column('student_answer', 'book')
    # ### end Alembic commands ###
