"""observers table added

Revision ID: 345d30f42d65
Revises: 0dd23c5cac46
Create Date: 2020-07-27 13:19:30.571789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345d30f42d65'
down_revision = '0dd23c5cac46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observers',
    sa.Column('observer_id', sa.Integer(), nullable=True),
    sa.Column('observed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['observed_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['student.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observers')
    # ### end Alembic commands ###
