"""added favorite color to student

Revision ID: 5590720eb171
Revises: 8673213417d2
Create Date: 2020-07-01 10:29:45.878835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5590720eb171'
down_revision = '8673213417d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('fav_color', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'fav_color')
    # ### end Alembic commands ###
