"""Added BugReport to Models

Revision ID: 9adc1c063a23
Revises: 9fc45108bdb4
Create Date: 2020-07-29 12:57:38.501316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adc1c063a23'
down_revision = '9fc45108bdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=200), nullable=True),
    sa.Column('seed', sa.Float(), nullable=True),
    sa.Column('question_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug_report')
    # ### end Alembic commands ###
