"""first and last name added to student model

Revision ID: 9fc45108bdb4
Revises: 345d30f42d65
Create Date: 2020-07-27 14:11:40.372240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc45108bdb4'
down_revision = '345d30f42d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('student', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'lastname')
    op.drop_column('student', 'firstname')
    # ### end Alembic commands ###
