"""Added books to Student model

Revision ID: e00f65ef016c
Revises: 9adc1c063a23
Create Date: 2020-07-30 22:20:11.151281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00f65ef016c'
down_revision = '9adc1c063a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('books', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'books')
    # ### end Alembic commands ###
