"""Re-initialized yet again --  can't delete columns??

Revision ID: e2edeb1251bc
Revises: 
Create Date: 2020-07-01 11:07:07.770600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2edeb1251bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('fav_color', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_username'), 'student', ['username'], unique=True)
    op.create_table('student_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=200), nullable=True),
    sa.Column('intended_answer', sa.String(length=200), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grade_category', sa.String(length=20), nullable=True),
    sa.Column('skillname', sa.String(), nullable=True),
    sa.Column('seed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_answer_timestamp'), 'student_answer', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_answer_timestamp'), table_name='student_answer')
    op.drop_table('student_answer')
    op.drop_index(op.f('ix_student_username'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
