"""Added User Section Interaction Model

Revision ID: e34e4b37506f
Revises: e00f65ef016c
Create Date: 2020-12-05 15:25:24.187853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34e4b37506f'
down_revision = 'e00f65ef016c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_section_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('masteries_count', sa.Integer(), nullable=True),
    sa.Column('last_mastery', sa.DateTime(), nullable=True),
    sa.Column('time_of_last_record', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('underway', sa.Boolean(), nullable=True),
    sa.Column('underway_seed', sa.Float(), nullable=True),
    sa.Column('underway_question_name', sa.String(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_section_status')
    # ### end Alembic commands ###
